### ISSUE TITLE
Fix history.json

### ISSUE THREAD

**Issue by Sinus44** [Sinus44/wordlepy#1]
Если файл history.json отсутствует, то при открытии сцены History возникает ошибка 

```
Traceback (most recent call last):
  File "C:\Users\инет\Desktop\wordlepy-1.3.0\main.py", line 5, in <module>
    app.start()
  File "C:\Users\инет\Desktop\wordlepy-1.3.0\application.py", line 44, in start
    self.scene_controller.start()
  File "C:\Users\инет\Desktop\wordlepy-1.3.0\scenectrl\contoller.py", line 146, in start
    self.draw_wrapper()
  File "C:\Users\инет\Desktop\wordlepy-1.3.0\scenectrl\contoller.py", line 122, in draw_wrapper
    self.event_wrapper(pygame.event.get())
  File "C:\Users\инет\Desktop\wordlepy-1.3.0\scenectrl\contoller.py", line 118, in event_wrapper
    self.scenes[self.selected_scene_name].event(event)
  File "C:\Users\инет\Desktop\wordlepy-1.3.0\scenes\menuscene.py", line 23, in event
    layout.event(event, self)
  File "C:\Users\инет\Desktop\wordlepy-1.3.0\gui\layout.py", line 29, in event
    if child._event(event, sender):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\инет\Desktop\wordlepy-1.3.0\gui\element.py", line 250, in _event
    if self.__on_click(event, sender):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\инет\Desktop\wordlepy-1.3.0\gui\element.py", line 261, in __on_click
    if on_click_handler(event, self):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\инет\Desktop\wordlepy-1.3.0\scenes\menuscene.py", line 14, in history_button_click
    self.app.scene_controller.select_scene("history")
  File "C:\Users\инет\Desktop\wordlepy-1.3.0\scenectrl\contoller.py", line 104, in select_scene
    self.scenes[self.selected_scene_name].select()
  File "C:\Users\инет\Desktop\wordlepy-1.3.0\scenes\historyscene.py", line 17, in select
    self.games = history.History.load()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\инет\Desktop\wordlepy-1.3.0\history.py", line 9, in load
    with open(History.FILE_PATH) as file:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'history.json'
```

**Comment by Sinus44** [comment]
fixed in [1.3.0 pre 5](https://github.com/Sinus44/wordlepy/commit/1bb8303fa60ec2bd11b494718d6cdc7ebf2d8fd7)
